### ISSUE TITLE
Reformatting

### ISSUE THREAD

**Issue by XeniaMonika** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#138] opened 2022-10-24 12:03 UTC
@theodore-s-beers  I´m having some problems with my workflow, as I usually work in a copy folder and than move the changes to the original one and push it from there. I do so, because I´m still learning and sometimes it happens that I mass up all files by accident... That why I prefer to work on a copy. But every time I want to save the changes to the original it reformats the files back to the old way. 
But that´s not a problem, I will find a workaround. The weird thing is that after I run npm run format form Power Shell to reformat the files back to prettier after they went through my script, it made some awkward changes, like converting Sixteenth back to Sexteenth or adding random spaces at the beginning or the end of strings. Can you have a look at it? You can see it in my PR

**Comment by theodore-s-beers** [comment] 2022-10-24 13:05
Is it possible that you were working from a local directory that didn't have some of my recent changes merged yet? It isn't a big deal; the misspelling and the extra spaces are just reverting fixes that I had pushed in the last few days.

If you look at your PR again, you'll see that I've added a commit to it to deal with those problems. In the end, it appears that you made only one change: removing a period at the end of a date. Is that right? If the diff looks correct to you now, feel free to merge the PR. It's good that you're paying attention to these things.

Using Git can be confusing, especially when there are multiple devs working on a repo. You can visit this page for troubleshooting tips and moral support: <https://ohshitgit.com/>

**Comment by XeniaMonika** [comment] 2022-10-24 13:19
Yes, I´ve seen your commit, and yes, I just removed a period.
I am working with a copy of dir that had your changes, but the problem lies in my script rewriting all files all over again...  Right now, I am trying to change it and to come up with a new workflow.  I have to rewrite my script and it may take some time, so probably I will not add much changes today.

**Comment by XeniaMonika** [comment] 2022-10-24 13:25
[That´s a cool webiste](https://ohshitgit.com/)! Thank you :)

**Comment by theodore-s-beers** [comment] 2022-10-24 13:28
That's interesting. The script must have had access to a copy of the repo, somewhere, that didn't yet have those fixes incorporated.

Another problem that can happen is that the actions performed by a script depend upon the directory from which it is executed. So it could also be a question of which directory you had open in PowerShell at the time.

**Comment by XeniaMonika** [comment] 2022-10-31 11:03
Do you think we can make prettier format only the new files by commit? [Could that be a solution?](https://stackoverflow.com/questions/47610213/how-do-i-run-prettier-only-on-files-that-i-want-to-commit) I have lots of files and running prettier on all of them is takes too much time and is unnecessary.

**Comment by theodore-s-beers** [comment] 2022-10-31 11:24
There are different possible solutions, but I'm wondering why Prettier would take a long time to go over the files in our project. It's not such a large number, and Prettier should be able to pass quickly over files that haven't changed (i.e., those that are already formatted properly). Could you maybe paste some command output here so that I can get an idea of what's going on?

**Comment by XeniaMonika** [comment] 2022-10-31 14:00
Do you mean this? 

PS H:\Git\Projects\PROJECTS> npm run format

> closing-the-gap@0.1.0 format
> prettier --ignore-path .gitignore --write .

.github\dependabot.yml 641ms
.github\workflows\validation.yml 14ms
ARCHIVE\_PROJECTS\alea\d0f460bf-e890-4124-95e5-03675d5d2a83.json 933ms
ARCHIVE\_PROJECTS\dariah_teach\502131b8-2103-465d-b49c-eaa0ca7d976b.json 37ms
ARCHIVE\_PROJECTS\digi_pal\e9ddf49e-4dc1-4f1c-ac73-ba0883cdd5d2.json 37ms
ARCHIVE\_PROJECTS\embedding_conquest\597655c6-ea3a-45b7-ba80-ea01d5fc2c49.json 10ms
ARCHIVE\_PROJECTS\futureit\f86f04d9-e28d-4d1b-8217-03d7594997d2.json 19ms
ARCHIVE\_PROJECTS\script_styles_versus_dialect_and_language\96c7995f-dfc8-489c-baf3-c4347b67c6db.json 25ms
ARCHIVE\_PROJECTS\the_persian_documents_from_al_haram_al_sarif\c0d5f0ed-cd33-4224-bcc9-d386f23b6446.json 33ms
ARCHIVE\_RESOURCES\resource.schema.json 35ms
ARCHIVE\_RESOURCES\RESOURCES.json 136ms
KEYWORDS_DOCUMENTATION.md 789ms
keywords_new.json 16ms
package-lock.json 9ms
package.json 4ms
PROJECTS.json 52ms
PROJECTS\a_digital_synopsis_of_the_mishnah_and_tosefta\71ff37e4-7e16-4c1f-b0a9-9bf47778d41f.json 33ms
PROJECTS\a_digital_typology_of_arabic_documents\72bf1192-8af5-4df0-bd88-cf4d62d13d66.json 13ms
PROJECTS\acdc\5e7ab61a-0c33-44fc-8175-a1930e6d08bc.json 26ms
PROJECTS\ada_center\173631fa-ddc3-4762-bfd9-5bf40ccef41a.json 21ms
PROJECTS\afrikanische_stimmen_in_islamischen_manuskripten\eaf36ccc-5ee4-4749-80ea-7f71f479c968.json 24ms
PROJECTS\al_turayya_project\8682a8f5-b601-4a6c-808c-aa4b7ce8a7c4.json 17ms
PROJECTS\altaegyptisches_woerterbuch\a4d189e4-f03f-4db0-8742-b777e22da760.json 15ms
PROJECTS\anonym_classic\d1e6d69b-5e9a-4b4a-85ad-09aac56ed2d9.json 25ms
PROJECTS\arabic_latin_corpus\e52825b6-9bd6-4206-b99c-964521b5e773.json 13ms
PROJECTS\arabic_latin_glossary\6a7e308d-0588-40b5-9a22-09354d313806.json 9ms
PROJECTS\arabic_papyrology_database\e9bf3427-1c16-4bec-9d2d-22836ae7a4b9.json 19ms
PROJECTS\arbeitsstelle_kleine_faecher\4a8c71d9-bdf0-4df1-9980-b13fb5b1af3b.json 14ms
PROJECTS\arche\a0e93701-b975-4760-b3cc-0204f54be3d1.json 7ms
PROJECTS\arches\ce6e74fb-c872-4ab4-a6f2-908232d0099a.json 25ms
PROJECTS\averroes_commentary_on_the_physics_in_hebrew_and_latin_transmission\3992a23d-8426-4b73-8b30-844e471e76e2.json 18ms
PROJECTS\averroes_de_partibus_animalium_and_de_generatione_animalium\7c7438e6-4172-4059-ad60-54a6d0d61f7c.json 15ms
PROJECTS\averroes_edition\a6e1fb68-e7a5-4125-8cfc-ec3aa16da73b.json 18ms
PROJECTS\averroes_ibn_baggas_de_generatione_et_corruptione\c3e206ec-9989-4500-ac20-4126e35871f2.json 15ms
PROJECTS\averroes_ibn_baggas_physics\f24e806a-0777-4690-b148-1b35ab3745e2.json 13ms
PROJECTS\babmed\942e9692-8e2a-4060-84d8-c8db17eae689.json 13ms
PROJECTS\beta_masaheft_manuscripts_of__ethiopia_and_eritrea\169677fd-14f9-46e7-b8f1-2202fb91397c.json 20ms
PROJECTS\biblia_arabica\c523675a-0e54-4d1e-8d08-2395d58323e3.json 12ms
PROJECTS\bibliotheca_arabica\ab7e5659-177f-40ed-befb-5d0eecea737f.json 16ms
PROJECTS\bildverarbeitung_bestimmung_von_visuellen_manuskript_und_zeichenmerkmalen\eb8e91fe-952e-48b7-af0d-c026ebe37826.json 9ms
PROJECTS\bldcil\614f4c99-0d96-48a9-baa5-48a402a8deec.json 14ms
PROJECTS\borno_and_old_kanembu_islamic_manuscripts\b485ffeb-bcbc-42a0-b141-4450ddc914e6.json 22ms
PROJECTS\cambridge_digital_library\13e5f8fd-9d40-4ae8-889c-0ee97316054d.json 10ms
PROJECTS\cdli\b8097890-6eeb-43ba-890d-28e1490fde08.json 13ms
PROJECTS\change_projekt\f87c6596-0ce3-4f2e-8ec5-ea5d17253bba.json 9ms
PROJECTS\clariah_de\842dc7b3-020c-47ea-a37e-d5e5aae0bde0.json 19ms
PROJECTS\clarin_d\b5604b8b-e9fa-43d3-af0d-ef287cc2fee7.json 13ms
PROJECTS\clarin\7e14a810-7d07-4e60-96eb-01fccf9323e8.json 35ms
PROJECTS\cls_infra\894f2c88-1713-480d-99cd-32d30f3c0ac2.json 18ms
PROJECTS\colophons_in_sumerian_and_akkadian\95a2024b-9fea-4ced-8136-1130b0fb8f51.json 13ms
PROJECTS\coranica\5f57a071-60c1-4fd2-b191-8fa8d15d70bb.json 14ms
PROJECTS\corpus_builder\eb1591d7-75b9-4d62-9f67-0679e627587b.json 12ms
PROJECTS\corpus_coranicum\0fd7b9cd-fdae-441b-a6fd-a791d4583ce0.json 12ms
PROJECTS\corpus_masoreticum\1c38b421-95a2-4b2b-becf-119f36721a07.json 14ms
PROJECTS\corpus_musicae_ottomanicae\5838a872-ff79-4e68-afff-edd784b0952e.json 12ms
PROJECTS\correspsearch\8779bc56-8526-4d03-85a7-702a03bcf748.json 7ms
PROJECTS\dariah_de\ea8a1aa5-a2a1-4d4a-9254-f647158c66fa.json 6ms
PROJECTS\dariah\1ae31b2f-5c67-49a7-9fba-c162b314bbcb.json 17ms
PROJECTS\datenrepositorium_manuskriptkulturen\894dcf0c-7295-4fb8-b4ba-866a5ebe3310.json 13ms
PROJECTS\demarginalizing_medieval_africa\46121edb-516b-4dbf-ba49-e2c5f07cec2e.json 14ms
PROJECTS\der_bibeltext_der_handschriften\9ed78f16-e6fa-4156-a03d-f6581b7b7367.json 10ms
PROJECTS\dhimmis_and_muslims\5c1c0e5b-cb6c-4d8e-9d1e-55e622a3ca40.json 17ms
PROJECTS\digital_corpus_for_greco_arabic_studies\2dfb544c-cf82-11ec-9d64-0242ac120002.json 15ms
PROJECTS\digital_edition_of_the_coptic_old_testament\1b19963e-ffc5-48f0-a1b3-81553d601497.json 12ms
PROJECTS\digital_sirah_project\3ecaadc2-5394-11ed-bdc3-0242ac120002.json 15ms
PROJECTS\digitalisierung_der_handschriften_ubl_1\0a75cf74-9cbe-4ce2-9799-ee16dcc1e88e.json 7ms
PROJECTS\digitalisierung_der_handschriften_ubl_2\cad00fa7-09a1-4df1-a08b-4ab5b2a48703.json 12ms
PROJECTS\dobes\e480a0fe-f152-11ec-8ea0-0242ac120002.json 13ms
PROJECTS\documentation_of_gorani\17fa004d-c9d2-4ce3-8116-b7bfff5d14ed.json 6ms
PROJECTS\doha_historical_dictionary\6f32aa08-b11d-48f4-8a9d-8f76738dc62e.json 16ms
PROJECTS\e_scriptorium\31ad93ff-ca97-4cf0-b30c-60685624e2c8.json 12ms
PROJECTS\elexis\43f49ea7-ec28-4e08-9ff4-57de8c755acd.json 12ms
PROJECTS\evolution_of_islamic_societies\659c0aba-3bdd-43eb-937d-dad4ad63e3fc.json 14ms
PROJECTS\fdnext\2fd5c31a-17a5-41ea-ae62-b6c2d3921cf5.json 14ms
PROJECTS\genesis_rabbah_loanwords\94044a63-eae5-4e1d-ba04-64874109fc36.json 9ms
PROJECTS\glossarion\ee6404e6-57f0-4e11-bb4a-1bbd13b08cb7.json 16ms
PROJECTS\glossarium_graeco_arabicum\7a287a76-c663-413d-9e3e-3191b1d6093e.json 13ms
PROJECTS\grasping_the_world_in_ottoman_istanbul\d1f743f2-7e94-4e00-a8bf-f46e56c7508e.json 5ms
PROJECTS\handschriftenportal\d0a1971a-e11b-442f-ab1a-6d8d421422c5.json 19ms
PROJECTS\hannah_arendt_digital\5f9179dc-cfdf-442b-b4a4-73ebf2f6256d.json 13ms
PROJECTS\hist-me\85590bb4-4b9a-49c9-8e41-d548a7d234e1.json 13ms
PROJECTS\hmml\52ce273e-7935-42fd-82e8-806f6aaa3049.json 11ms
PROJECTS\humanweb\1a587e85-1385-40b0-b6eb-25ca8fa5042c.json 13ms
PROJECTS\hunaynnet\70944a30-3932-46bb-8c3f-410a48d9e0b9.json 8ms
PROJECTS\ibn_nubata_gesamtedition\04ea57c8-69c7-4c83-8249-753850e9cc53.json 13ms
PROJECTS\intersame\bb852d81-0c6d-4413-8c20-1bb38c4db4e7.json 10ms
PROJECTS\irankoran\8e4ab5b4-7298-4d55-b490-eb2943527981.json 13ms
PROJECTS\islamic_painted_page\31534c48-6b74-4cc5-8aff-ea8dbc60c445.json 8ms
PROJECTS\kallimachos\5755bad5-4162-48ce-84b4-997819fa61b7.json 7ms
PROJECTS\keywords\c82cb342-bf56-48ac-b910-f5c9a440b06e.json 7ms
PROJECTS\kitab\d4d49850-4711-4d43-97e9-c3563626d8df.json 13ms
PROJECTS\kohd_digital\01ac0c0c-b09c-40cf-a75f-42e540b67c2f.json 6ms
PROJECTS\kompetenzwerk_d\6c5643df-bfb8-48e8-a7c6-473146cf497d.json 7ms
PROJECTS\majlis\583ab46e-ccb8-4a49-9912-7771683cd605.json 11ms
PROJECTS\mela\377201a9-9b09-4a6b-b5e8-873190633e78.json 12ms
PROJECTS\methoden_der_manuskriptanalyse_zur_wiedergewinnung_verlorener_schrift\892b783d-1788-451f-9efd-1c58bfb4b064.json 12ms
PROJECTS\multi_cast\b37c6bd1-90d3-4718-ab58-fb1d60873186.json 13ms
PROJECTS\nomansland\e050deba-6e1d-4d82-851b-cf6c1f7187a5.json 4ms
PROJECTS\onomasticon_arabicum\ddbb569b-1542-40fe-9fa7-3842610945c8.json 13ms
PROJECTS\open_encyclopedia_system\2860c96f-323e-4c33-97c6-4219bcf99f52.json 7ms
PROJECTS\open_iti_aocp\786edd87-476e-42a6-bcc0-521833ec73e5.json 13ms
PROJECTS\open_iti\bef2e507-b663-422e-9dd3-7e49ca299f05.json 16ms
PROJECTS\orient_digital\a4fa5143-90d2-42ba-a8a1-424b09696b1c.json 15ms
PROJECTS\pal_read\2adf7ddc-9dd5-49b3-842c-9dc48dbbf36e.json 12ms
PROJECTS\paleocoran\d5448b02-b57f-429d-9553-637cc2add035.json 7ms
PROJECTS\patterns_of_knowledge_circulation\c2c309a5-923c-4759-ae83-f870b10dceff.json 8ms
PROJECTS\post_predicate_elements_in_iranian\c1a2957b-0c24-46e6-9a67-381997525a87.json 16ms
PROJECTS\pre_19th_century_kurmanji_kurdish\d0bda69f-d8c4-4521-ab18-af2c097ffcfc.json 9ms
PROJECTS\ptolemaeus_arabus_et_latinus\a9ca5d9f-47ab-4704-ad27-9a09e492ca2a.json 22ms
PROJECTS\pudel\3c5fd869-4651-414c-a0f1-b1254712b689.json 13ms
PROJECTS\qalamos\3c5b84d0-791c-43bc-ab68-7372478bc568.json 12ms
PROJECTS\qhod_die_großbotschaften\ff1ec94f-2233-46e9-b550-45c792ae581e.json 10ms
PROJECTS\qhod_die_schreiben_selims_ii\e9b15bcd-05ec-4de1-95f5-07d5bb44e482.json 15ms
PROJECTS\qhod\6298a9cd-d41a-40d8-91d0-c532692e95c9.json 6ms
PROJECTS\qumran_digital_text_und_lexikon\99718590-5e1e-4a64-bf84-6e2213ad1836.json 13ms
PROJECTS\refaiya\38e6dfb4-730a-4a80-8090-4b7ea551b3c7.json 14ms
PROJECTS\romantic_period_poetry_archive\32bc596c-eafd-4bd2-8df3-f1ab5cff4ad6.json 12ms
PROJECTS\sabaweb\9078ff92-18f1-4019-a9f3-8c7d9aaa0db8.json 9ms
PROJECTS\saop\87d036b9-5145-47d0-8d0e-83bb6821f3fe.json 20ms
PROJECTS\scripta_psl\0cf58379-39c3-4e95-b7b1-cc9f7f11c7ba.json 15ms
PROJECTS\scripta_qumranica_electronica\9513964d-3509-462e-9d64-c47fd3922459.json 16ms
PROJECTS\sefaria_org\177501b1-c847-4547-a757-76f56c5af15f.json 9ms
PROJECTS\sfardata\81d8ad85-5da8-457f-99a3-6ab11128ef03.json 10ms
PROJECTS\sharia_source\1b2ca0bf-fb29-4b5c-852b-2eedd6a85773.json 13ms
PROJECTS\shawi\68422d65-ccba-4dcb-8a0e-bd4f3f9e1dc9.json 9ms
PROJECTS\snapdrgn\fb67cd77-6bc3-41a8-a84c-05bb2a5d1dd0.json 8ms
PROJECTS\streamlining_galen\880f1d65-b815-4474-9fb4-b17f13bd3765.json 13ms
PROJECTS\strukturen_und_transformationen\85d053c3-4ce6-4130-bc6a-63f96acfb067.json 6ms
PROJECTS\synoptische_edition_des_kabbalistischen_traktats_keter_shem_tov\827f5ce7-a331-44fe-b40a-5cd93f348a0a.json 7ms
PROJECTS\syriaca_org\fdda3e43-e15b-4c64-a99d-924f37152cc9.json 10ms
PROJECTS\text_plus\2689651d-1e28-4f26-ac43-cfdca097d837.json 12ms
PROJECTS\the_formation_of_islam\33a6a747-4180-4e28-a99c-2bf6dcf53200.json 13ms
PROJECTS\the_islamic_manuscript_association\862e636c-6757-4dc6-a382-b77768b69cbc.json 7ms
PROJECTS\the_literary_history_of_medicine_online\e9e4a759-5a0c-4d7d-aa61-49051477ab2f.json 8ms
PROJECTS\tikkoun_sofrim\ce4fc765-1578-4cfb-8efa-b82387c99590.json 7ms
PROJECTS\topoi\b583a2f6-22bb-4ddb-8639-c9a9aa7b511b.json 9ms
PROJECTS\tunico\79462111-75a7-4fa0-8e11-9d424293a074.json 7ms
PROJECTS\tunocent\325a929a-6764-41e1-b452-6556209fa74f.json 8ms
PROJECTS\understanding_written_artefacts\9ca46873-3089-4a04-99fa-89c0c1b01213.json 10ms
PROJECTS\verse_und_sprueche\a2984fec-9396-488e-ad56-d3d21dc49052.json 9ms
PROJECTS\vicav\8f343a28-a873-449c-b359-efcfab7d1201.json 9ms
PROJECTS\virtuelle_archive_für_die_geisteswissenschaftliche_forschung\fcbda96b-0c65-4ac9-9047-bde2323a0cb4.json 19ms
PROJECTS\wibarab\e9cb8ab1-2d2c-4cc3-a44d-a793220a8638.json 15ms
PROJECTS\wissensgemeinschaften\5f3c2fbb-ca17-41c9-acdb-d3e147869400.json 7ms
PROJECTS\ymdi\e17c5b2a-7619-40bd-bddd-51063f687cb0.json 10ms
README.md 59ms
SCHEMATA\project.schema.json 42ms
TEMPLATES\project_proposal.json 42ms
TEMPLATES\project.json 26ms

**Comment by XeniaMonika** [comment] 2022-10-31 14:02
It takes maybe 3 min, is it long? I could be bcs of the vpn maybe. But if you said, that 3 min are ok, then I can leave it. I have a new script right now, so I hope it the things will work better!

**Comment by theodore-s-beers** [comment] 2022-10-31 15:09
Minutes is bad. It should run in seconds. The JSON files are mostly reporting formatting times under 20 ms. Even with a couple hundred files, that should only add up to a few seconds. I wonder what the problem is…

**Comment by XeniaMonika** [comment] 2022-10-31 15:45
Ok... When I work with the VPN everything is generally very slow. Even git, when I call git status, it usually takes half a minute to respond. I don´t know

**Comment by XeniaMonika** [comment] 2022-10-31 15:49
Maybe we can talk about it on Thursday. Besides that my own workflow is all set up now.

**Comment by theodore-s-beers** [comment] 2022-10-31 16:01
Maybe your working directory is on a remote drive? That could cause major slowdowns.

**Closed** 2022-11-04 09:35 UTC
