### ISSUE TITLE
Broken link in the main README

### ISSUE THREAD

**Issue by Maroussia** [M-L-D-H/Closing-The-Gap-In-Non-Latin-Script-Data#176] opened 2022-11-22 10:15 UTC
I tried the link under `contribution` in `README.md` and it led to a 404 - Page not found, although the link seems right. Any idea why this is happening?

The link to the website above on the same `README` works perfectly.

Thanks for looking into it!

**Comment by theodore-s-beers** [comment] 2022-11-22 11:58
Yeah, the problem is that links to specific pages within the website don't currently work as standalone URLs. You have to go to the main page and then navigate to where you want. For example, the "About" page can't be accessed directly, either:

<https://m-l-d-h.github.io/Closing-The-Gap-In-Non-Latin-Script-Data/about>

I'm working on a new version of the front end that will not have this problem:

<https://ctg-redux.pages.dev/about>

We're using issue #169 to track the reimplementation of the front end. So I'll close this issue, though the fix is still in progress. Thanks for reporting.

**Closed by theodore-s-beers** 2022-11-22 11:58 UTC
